### ISSUE TITLE
connection not working for postgres backend

### ISSUE THREAD

**Issue by rgangaderan** [metal-stack/go-ipam#137]
unable to connect to database:dial tcp 127.0.0.1:5432: connect: connection refused

**Comment by majst01** [comment]
`connection refused` comes from your operating system, this means no open port on 127.0.0.1:5432, please check your configuration

**Comment by majst01** [comment]
You struggle with the basics of container networking, inside the go-ipam container there is no one listening on localhost:5432. Instead, depending on your local docker network configuration, it will be reachable at 172.17.0.1:5432.

Please read https://docs.docker.com/network/ and try with these insights.

**Comment by rgangaderan** [comment]
if this is the case, let's say that I use docker run -it --rm ghcr.io/metal-stack/go-ipam postgres f for use file backend
and I only see 
{"time":"2024-03-14T06:21:06.205190227Z","level":"INFO","msg":"starting go-ipam","version":{},"backend":"file"}
{"time":"2024-03-14T06:21:06.206083937Z","level":"INFO","msg":"serving metrics","at":"localhost:2112/metrics"}

and when run the `docker run -it --rm --entrypoint /cli ghcr.io/metal-stack/go-ipam ip release` the error is there for 9090 port, I even try to update  

unavailable: dial tcp 127.0.0.1:9090: connect: connection refused

**Comment by majst01** [comment]
Created a PR which explains the usage with `docker compose`, will be merged next week, but you can have a look and give feedback

https://github.com/metal-stack/go-ipam/pull/139

**Comment by rgangaderan** [comment]
Yes, the docker compose is working fine with all the testings!!!!! thank you!!!!!!

**Comment by rgangaderan** [comment]
Thank you!
