### ISSUE TITLE
ipam not working with etcd service

### ISSUE THREAD

**Issue by rgangaderan** [metal-stack/go-ipam#145]
I have ran the etcd on my local mac and I can curl without an issue, I tried to access ipam with edcd backend using a docker compose file and getting an error

{"level":"warn","ts":"2024-05-05T11:58:26.550315Z","logger":"etcd-client","caller":"v3@v3.5.11/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x400037a8c0/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""}
ipam-1  | 2024/05/05 11:58:26 Error in cli: context deadline exceeded
ipam-1 exited with code 1

`  ipam:
    image: go-ipam
    environment:
      - GOIPAM_GRPC_SERVER_ENDPOINT=0.0.0.0:9090
      - GOIPAM_ETCD_HOST=localhost
      - GOIPAM_ETCD_PORT=2379
      # - GOIPAM_ETCD_CERT_FILE=cert.pem
      # - GOIPAM_ETCD_KEY_FILE=key.pem
      - GOIPAM_ETCD_INSECURE_SKIP_VERIFY=false
    restart: always
    command:
      etcd
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr","localhost:9090"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s`
      
this is a part of the compose file I used.

**Comment by majst01** [comment]
it say connection refused, which means there is no etcd listening on the port 2379

**Comment by rgangaderan** [comment]
my bad I was deployed this with wrong network 
it's working now
