### ISSUE TITLE
Can this ipam support prefix alloction with start_ip and end_ip for the pool?

### ISSUE THREAD

**Issue by gotostack** [metal-stack/go-ipam#167]
For instance, if we have a CIDR 192.168.1.0/24, but we only want the IP allocation starts at 192.168.1.10, and end to 192.168.1.200.
Am i missing something? Can we achive this?

**Comment by majst01** [comment]
This is not a built in feature, but we at metal-stack.io have the same requirement and simple pre-allocate ips at the beginning and at the end of the CIDR to prevent others from doing so.

**Comment by Gerrit91** [comment]
I hope that this works, if still required please re-open.
