### ISSUE TITLE
Create high level functions or specific error's

### ISSUE THREAD

**Issue by ulrichSchreiner** [metal-stack/go-ipam#19]
hi,

in `metal-api` we have some cleanup code that looks like this:
~~~go
// release and delete
	err := a.ReleaseIP(*ip)
	if err != nil {
		return fmt.Errorf("cannot release IP %q: %w", ip.IPAddress, err)
	}
	err = a.DeleteIP(ip)
	if err != nil {
		return fmt.Errorf("cannot delete IP %q: %w", ip.IPAddress, err)
	}
~~~
the problem with the `ReleaseIP` and the `DeleteIP` is that they only return errors or OK. but the caller does not know if the error can be ignored or not.

suppose a function which does the upper block until it success. this is a problem if the `ReleaseIP` succeeds but the `DeleteIP` does not. In this case the next call of this block will fail with the `ReleaseIP` because the previous call to this code already released the IP. So the `DeleteIP` will never be reached again.

  - the functions should return specific error-codes like `NotFound` so the caller can ignore this specific errors. 
--- OR ---
  - the library should contain higher level functions like `ReleaseAndDeleteIP` which work with one transaction and they succeed or fail.

**Comment by majst01** [comment]
I´d prefer the second approach, but in go-ipam there is no such function DeleteIP, there is only ReleaseIP. I guess this is lower level code in metal-api

**Comment by majst01** [comment]
Yes, ReleaseIP is go-ipam, DeleteIP is metal-api datastore. So the only solution would be to make the error distinguishable

**Comment by ulrichSchreiner** [comment]
yes you're right. `DeleteIP` is from metal-api, so better error codes would be nice.

another idea are contexts which contain the transaction. this would make the transaction boundaries visible to the user of the ipam. somethink like this:
~~~
ctx, rollback, commit := ipam.NewContext()
ipam.ReleaseIP(ctx, ip)
...
commit()
// or rollback() if an error occured
~~~
in this case every ipam function needs an additional parameter with a context which itself stores a transaction. so the user is able to do the tx-handling. the disadvantage is: the user **has to** handle the transactions.

**Comment by majst01** [comment]
I vote for a two fold process:
1. we change the relevant functions to return meaningful errors
2. add context, i like this approach, the user can still decide how to cope with error situations, either doings his own transactions or leave it as is.

WDYT ?
I already have a branch with some improvements regarding errors, will try.
