### ISSUE TITLE
AcquireSpecificIP will block forever if IPv6 is already taken

### ISSUE THREAD

**Issue by thetechnick** [metal-stack/go-ipam#47]
Hey everyone!
I am playing around with this library in my IPAM controller for Kubernetes https://github.com/routerd/kube-ipam.

Today I stumbled across a strange Bug.
When a specific IPv6 address is already allocated `AcquireSpecificIP` will block forever...
(or at least longer than I am patient for :D -> 5min+ )

Hope I am not just grossly misusing this library :)

Tested on `v1.8.1` according to `go.mod`
```
$ go version
go version go1.15.8 linux/amd64
```

Here is a little go-snippet that I have used to reproduce the issue:
```go
const (
	cidr = "fd9c:fd74:6b8d:1020::/64"
)

func main() {
	ipam := goipam.New()
	ipam.NewPrefix(cidr)

	ip1, err := ipam.AcquireSpecificIP(cidr, "fd9c:fd74:6b8d:1020::1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip1)

	ip2, err := ipam.AcquireSpecificIP(cidr, "fd9c:fd74:6b8d:1020::1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip2)
}
```

will return:
```
$ go run ./ipv6/main.go 
got static:  &{fd9c:fd74:6b8d:1020::1 fd9c:fd74:6b8d:1020::/64}
< blocks forever >
```

The same code using IPv4 is working fine:
```go
const (
	cidr = "172.20.0.0/24"
)

func main() {
	ipam := goipam.New()
	ipam.NewPrefix(cidr)

	ip1, err := ipam.AcquireSpecificIP(cidr, "172.20.0.1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip1)

	ip2, err := ipam.AcquireSpecificIP(cidr, "172.20.0.1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip2)
}
```
```
$ go run ./ipv4/main.go
got static:  &{172.20.0.1 172.20.0.0/24}
NoIPAvailableError: no more ips in prefix: 172.20.0.0/24 left, length of prefix.ips: 3
exit status 1
```

**Comment by majst01** [comment]
Hi @thetechnick thanks for this detailed bug report. Indeed this case was not covered in the actual code, which didnt hurt in most ipv4 cases, because the ipv4 address space is much smaller. Please test with the branch from my PR.
This PR will be merged soon
