### ISSUE TITLE
Capability to allocate a specific child Prefix from a parent Prefix

### ISSUE THREAD

**Issue by davidefalcone1** [metal-stack/go-ipam#53]
It's not possible (or at least I cannot do it) allocate a specific child Prefix given a Parent: function AcquireChildPrefix does not allow you to specify a Prefix.
Are you planning to implement this feature?

**Comment by majst01** [comment]
We didnt have the need for this requirement, but im happy to review a PR if you are willing to provide one.
Should not be a big deal

**Comment by davidefalcone1** [comment]
I'm considering two alternatives: 
1. Create a new function (and an exported wrapper for it) called acquireSpecificChildPrefixInternal which is very similar to acquireChildPrefixInternal, with the exception that it does not invoke RemoveFreePrefix()
2. Modify the existing acquireChildPrefixInternal to get one more parameter(childCidr). If this parameter is the empty string, then it behaves like the original acquireChildPrefixInternal, otherwise it acquire a specific child prefix. This function is invoked by the exported functions AcquireChildPrefix and AcquireSpecificChildPrefix, with the right parameters. In this solution we should have less duplicated code.
What do you think?

**Comment by majst01** [comment]
option 2 sounds reasonable, but must see how big the impact is.
