### ISSUE TITLE
Stop globally setting log to discard output in init()

### ISSUE THREAD

**Issue by hugbubby** [metal-stack/go-ipam#55]
It took me a while to figure out that this was the package that had disabled all of my log messages. Your init() function runs for everybody that imports this library.

**Comment by majst01** [comment]
Good catch, this is because testing.go is not a test file, i will check howto prevent this ugly bug.

**Comment by majst01** [comment]
Can you please check if #56 resolves you problem ?

**Comment by majst01** [comment]
@hugbubby is you problem solved with #56 ?

**Comment by hugbubby** [comment]
@majst01 Yes, I think so.
