### ISSUE TITLE
Method in the `Ipamer` interface to fetch existing Prefixes

### ISSUE THREAD

**Issue by rene-at-dell** [metal-stack/go-ipam#68]
From what I could tell, the `Ipamer` interface is there to abstract out the `Storage` backend.

Wouldn't it make sense to have a method in the `Ipamer` interface to fetch existing CIDRs?

Only way I can see how to do it right now is via the `ReadAllPrefixCidrs()` method in the `Storage` interface.

Am I missing something?

**Comment by majst01** [comment]
There is already a `ReadAllPrefixes` method defined in the `Storage` interface. Exposing it would be possible.

May i ask what is the use case ? For Backup purposes i am preparing a `Dump` and `Load` Interface in this PR: #65, maybe this  already serves your purpose ? If not feel free to raise a  PR for that.

**Comment by rene-at-dell** [comment]
Exposing `ReadAllPrefixes` would also work but seems like overkill.  I mentioned `ReadAllPrefixCidrs` simply because it's more light weight and serves the purpose:

If you can get the CIDRs directly from the 'Ipamer`, then that would allow you to fetch a `Prefix` via the `PrefixFrom` method.  That in turn means you don't need the Storage for anything but initialization.  Seems like a simpler approach in the sense that it avoids you from having to carry around both the `Storage` and the `Ipamer` everywhere in the code.

Also, if you look at the example on the README that uses `New`, no way to get the list of Prefixes since you never get access to the underlying memory `Storage`.

Make sense?

**Comment by rene-at-dell** [comment]
Thanks @majst01
