### ISSUE TITLE
Is this lib stateless ready with Redis storage?

### ISSUE THREAD

**Issue by dzvancuks** [metal-stack/go-ipam#76]
I'm trying to implement IPAM in stateless environment using Redis as central DB. After analyzing [redis module](https://github.com/metal-stack/go-ipam/blob/master/redis.go) it seems that there will be racing and traffic congestion issues.

1. To AcquireIP() library first calls [ReadPrefix()](https://github.com/metal-stack/go-ipam/blob/981c10dab00e97b2138ad473e220efd11d420ebb/redis.go#L55). Then it locally fetches next available IP. After that [UpdatePrefix()](https://github.com/metal-stack/go-ipam/blob/981c10dab00e97b2138ad473e220efd11d420ebb/redis.go#L97) to write data back.
Problem here that another node might have called ReadPrefix() with same state and will try to attempt same UpdatePrefix()
2. UpdatePrefix() relates on ['optimistic lock'](https://github.com/metal-stack/go-ipam/blob/master/redis.go#L118-L121) by checking version. On failure (other node changed version) the whole process will be started again up to [10 times](https://github.com/metal-stack/go-ipam/blob/981c10dab00e97b2138ad473e220efd11d420ebb/prefix.go#L646).
Here I see that in case there are many nodes trying to work with same CIDR there will be racing condition. In the end current node can easily stumble on 10 retries and fail to allocate IP.
Also Redis locks data only on read-write operations. So [between version Read and updated prefix Write](https://github.com/metal-stack/go-ipam/blob/master/redis.go#L110-L124) operation another node might update same prefix data. This result that 2 nodes allocates same IP from CIDR pool and both will consider operation to be successful.
3. Traffic congestion on lock checks, retries.

Library is OK for single node operation, but won't do on multinode due to lack of syncronization. Easy and dirty solution would be [SETNX](https://redis.io/commands/setnx/) as a mutex. But this will slow operatons while other nodes wait for lock release.

There is also [PubSub](https://redis.io/docs/manual/keyspace-notifications/) model. Where nodes can passively watch for key chanes. This way nodes can track updates and react faster on them.

And finally we should keep in mind latency. Extra checks and retries increases traffic. Instead it is more preferable to [Pipeline or Script](https://redis.io/docs/reference/optimization/latency/#latency-induced-by-network-and-communication) Redis commands.

**Comment by dzvancuks** [comment]
Yes, I see that SQL storage uses transactions with commit/rollback action.

Updated title to emphasize Redis commands.

**Comment by majst01** [comment]
I would appreciate a pull request which will ensure the same guarantees for the redis storage

**Comment by dzvancuks** [comment]
I have to admit I missed the `Watch` command. It triggers transaction with similar to commit or rollback operations.

Sorry for that. I'll close issue.
