### ISSUE TITLE
mongodb storage backend

### ISSUE THREAD

**Issue by f00actual** [metal-stack/go-ipam#79]
I would like to add support for a mongodb storage back-end, and I'm also willing to contribute the code. I've tested it locally, with tests passing and benchmarks appearing favorable. Are you open to such a contribution? Cheers.

**Comment by majst01** [comment]
Sure i am open for contributions, i  am a bit worried about the indirect dependencies coming with mongodb: https://github.com/mongodb/mongo-go-driver/blob/master/go.mod

I am also unsure if the licenses are compatible, as i am not a laywer.

But go ahead, create a PR and show the numbers, i am really interested how mongodb compares for example to redis or postgres
