### ISSUE TITLE
Missing `AcquireSpecificIP` implementation in `IpamServiceClient`

### ISSUE THREAD

**Issue by nerdalert** [metal-stack/go-ipam#90]
Hi, first off, awesome project, you all have done a really nice job!! 

Quick question, are there plans to implement [AcquireSpecificIP](https://github.com/metal-stack/metal-api/blob/2ae0dd0c84c640bcbee48d3d048b6f8a3861af96/cmd/metal-api/internal/ipam/ipam.go#L96) in the grpc [IpamServiceClient](https://github.com/metal-stack/go-ipam/blob/master/api/v1/apiv1connect/ipam.connect.go#L29) Interface?

Looks like it accepts the /32 specific requested address in a prefix to lease but doesnt use it. `apiv1.AcquireIPRequest{...}`

Here we pass in a specific /32 but get returned  the next ip in the pool.

```go
	res, err := ct.ipam.AcquireIP(ctx, connect.NewRequest(&apiv1.AcquireIPRequest{
		PrefixCidr: ipamPrefix,
		Ip:         &nodeAddress,
	}))
```

Happy to hack, just wondering if this was a todo or specifically left out of the IpamServiceClient implementation. Thanks again for the neat project! 🥇

**Comment by majst01** [comment]
If the ip in the AcquireIPRequest is not nil it is considered as specific IP. But you are right, the implementation in ipam-service.go does not take this into consideration.

If you have time i would happily review a PR.

Thanks for reporting

**Comment by RealHarshThakur** [comment]
Ran into something similar with CIDRs. Would appreciate a review @majst01  :)  
 https://github.com/metal-stack/go-ipam/pull/98

**Comment by RealHarshThakur** [comment]
Yes!
